service: product-service
app: shop-react-redux-cloudfront-backend
#org: hamanovich

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  lambdaHashingVersion: 20201221

  stage: dev
  region: eu-central-1

functions:
  hello:
    handler: handlers/handler.hello
    events:
      - http:
          path: hello
          method: GET
          # cors: true

  getProductsList:
    handler: handlers/getProductsList.handler
    events:
      - http:
          path: products
          method: GET
          # cors: true

  getProductById:
    handler: handlers/getProductById.handler
    events:
      - http:
          path: products/{productId}
          method: GET
          request:
            parameters:
              paths:
                productId: true
          # cors: true